---
- name: gather diagnostic logs
  hosts: glusternodes
  tasks:
    - name: generate diagnostic archives
      shell: "{{ item }} > /dev/null 2>&1"
      ignore_errors: yes
      register: command_result
      with_items:
        - "/root/bin/backup-conf"
        - "/root/bin/backup-log"
        - "sosreport --batch --tmp-dir /root/backup --name {{ inventory_hostname }}"
    - name: copy diagnostic archives
      synchronize:
        mode: pull
        recursive: yes
        partial: yes
        src: /root/backup
        dest: "/root/backup/{{ inventory_hostname }}"
...
