---
# Ansible playbook to generate and gather logs from nodes
- name: Gather diagnostic logs
  hosts: glusternodes
  tasks:
    - name: Generate standard sosreport
      vars:
        generate_sosreport: false
      command: "sosreport --batch --tmp-dir /root/backup --name {{ inventory_hostname }}"
      ignore_errors: yes
      register: sosreport_result
      when: generate_sosreport
    - name: Generate custom storage status report
      script: files/inspect-node-storage.sh
    - name: Generate common HVP configuration/log archives
      shell: "{{ item }} > /dev/null 2>&1"
      ignore_errors: yes
      register: backupcommand_result
      with_items:
        - "/root/bin/backup-conf"
        - "/root/bin/backup-log"
    - name: Copy diagnostic archives locally
      synchronize:
        mode: pull
        recursive: yes
        partial: yes
        src: /root/backup
        dest: "/root/backup/{{ inventory_hostname }}"
...
