---
# Ansible playbook for automated oVirt VMs creation
# Note: Thanks to Simone Tiraboschi for initial Ansible oVirt management hints
# TODO: find a way to extract minimum desired parameters from local Kickstart file and use those for vm creation in loop
# TODO: remove all DHCPd custom entries (from /etc/dhcp/dhcpd-custom-pxe.conf) at the end
- name: Generate SSH key if not present
  hosts: localhost
  tasks:
    - include_tasks: ../common/tasks/createkeys.yaml
- name: Perform global oVirt operations through the Engine
  hosts: ovirtengine
  remote_user: root
  # TODO: there is a visibility/syntax error on using the global variables - trying to work around here
  pre_tasks:
    - name: Gather facts from all hosts (regardless of limit or tags)
      setup:
      delegate_to: "{{ item }}"
      delegate_facts: true
      with_items: "{{ groups['ovirtnodes'] }}"
  tasks:
    - include_tasks: ../common/tasks/setupkeys.yaml
    - name: Get common vars from files
      include_vars:
        file: "../common/vars/hvp.yaml"
    - name: Create all guest VMs
      include_tasks: tasks/createvm.yaml
      loop: "{{ guest_vms }}"
      loop_control:
        loop_var: outer_item
        label: "{{ outer_item.vm_name }}"
...
