---
- name: Generate SSH key if not present
  hosts: localhost
  tasks:
    - include: ../common/tasks/createkeys.yaml
- name: perform oVirt configuration
  hosts: ovirtengine
  remote_user: root
  tasks:
    - include: ../common/tasks/setupkeys.yaml
    - name: get common vars
      include_vars:
        file: ../common/vars/hvp.yaml
    - name: install the OVN-related packages
      yum:
        name: "{{ item }}"
        state: latest
      with_items: openvswitch openvswitch-ovn-common openvswitch-ovn-central python-openvswitch ovirt-provider-ovn
    - name: enable and start the OVN-related services
      systemd:
        name: "{{ item }}"
        enabled: True
        state: started
        no_block: no
      with_items: ovirt-provider-ovn
    - name: allow OVN-provider communications
      firewalld:
        service: ovirt-provider-ovn
        permanent: True
        immediate: True
        state: enabled
    - name: allow OVN-components communications - 1
      firewalld:
        rich_rule: 'rule family="ipv4" port protocol="tcp" port="6641" accept'
        permanent: True
        immediate: True
        state: enabled
    - name: allow OVN-components communications - 2
      firewalld:
        rich_rule: 'rule family="ipv4" port protocol="tcp" port="6642" accept'
        permanent: True
        immediate: True
        state: enabled
    - name: configure OVN central to listen on ports - 1
      shell: "ovn-nbctl set-connection ptcp:6641"
      register: centralconf1_result
    - name: configure OVN central to listen on ports - 2
      shell: "ovn-nbctl set-connection ptcp:6642"
      register: centralconf2_result
- name: perform OVN configuration on hosts
  hosts: ovirtnodes
  remote_user: root
  tasks:
    - include: ../common/tasks/setupkeys.yaml
    - include: ../common/tasks/securessh.yaml
    - name: get common vars
      include_vars:
        file: ../common/vars/hvp.yaml
    - name: configure OVN VIF driver
      shell: "vdsm-tool ovn-config {{ hostvars[groups['ovirtengine'][0]]['ansible_default_ipv4']['address'] }} {{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
      register: vifconf_result
...
