#!/usr/bin/python

import os

import hooking

from ovirt_hosted_engine_setup import constants as ohostedcons


class NestedInVMWareHook(object):

    def __init__(self):
        super(NestedInVMWareHook, self).__init__()
        self.config = {}
        self.domxml = hooking.read_domxml()

    def save(self):
        hooking.write_domxml(self.domxml)

    def set_custom_machine_type(self):
        os_element = self.domxml.getElementsByTagName('os')[0]
        os_type_element = os_element.getElementsByTagName('type')[0]
        machine_attr=os_type_element.setAttribute('machine', 'pc-i440fx-rhel7.2.0')

    def main(self):
        self.set_custom_machine_type()
        self.save()


if __name__ == "__main__":
    NestedInVMWareHook().main()


# vim: expandtab tabstop=4 shiftwidth=4
