---
# Ansible playbook to join the Gluster-based Samba clustered fileserver to the internal oVirt-hosted AD domain
- name: Generate SSH key if not present
  hosts: localhost
  tasks:
    - include_tasks: ../common/tasks/createkeys.yaml
    - name: Get common vars
      include_vars:
        file: "{{ item }}"
      with_items:
        - "../common/vars/hvp.yaml"
        - "../common/vars/ad.yaml"
    - name: Wait for full AD DC availability
      # Note: we wait for DNS, RPC, LDAP and Kerberos (password change) services to be listening on a DC (identified by resolving the AD domain DNS name)
      wait_for:
        host: "{{ lookup('dig', hvp_adjoin_domain, wantlist=True) | first }}"
        port: "{{ item }}"
        state: started
        delay: 0
        sleep: 30
        timeout: 300
      with_items:
        - 53
        - 135
        - 389
        - 464
- name: Perform Samba AD configuration
  hosts: glusternodes
  remote_user: root
  tasks:
    - include_tasks: ../common/tasks/setupkeys.yaml
    - name: Get common vars
      include_vars:
        file: "{{ item }}"
      with_items:
        - "../common/vars/hvp.yaml"
        - "../common/vars/ad.yaml"
    - name: Prepare Samba domain-based configuration file
      template:
        src: templates/smb-domain.j2
        dest: /etc/samba/smb.conf
        owner: root
        group: root
        mode: 0644
- name: Perform Samba cluster AD joining
  hosts: gluster_master
  remote_user: root
  tasks:
    - name: Obtain Kerberos ticket
      shell: |
        set timeout 300
        spawn kinit {{ hvp_adjoin_username }}@{{ hvp_adjoin_realm }}
        match_max 100000
        expect -re -nocase "password for.*:.*$"
        send -- "{{ hvp_adjoin_password }}\r"
        expect eof
      args:
        executable: /usr/bin/expect
    - name: Join AD domain
      shell: net ads join -k osName="$(lsb_release -si)" osVer="$(lsb_release -sr)"
      register: join_result
    - name: Remove Kerberos ticket
      command: kdestroy
      register: kdestroy_result
- name: Reload Samba configuration
  hosts: glusternodes
  remote_user: root
  tasks:
    - name: Signal Samba services to apply the configuration above
      command: smbcontrol all reload-config
      register: smbcontrolreload_result
...
