---
- name: perform Samba AD configuration
  hosts: glusternodes
  remote_user: root
  tasks:
    - name: get common vars
      include_vars:
        file: "{{ item }}"
      with_items:
        - "../common/vars/hvp.yaml"
        - "../common/vars/ad.yaml"
    - name: prepare Samba AD configuration file
      template:
        src: templates/smb-domain.j2
        dest: /etc/samba/smb.conf
        owner: root
        group: root
        mode: 0644
- name: perform Samba cluster AD joining
  hosts: gluster_master
  remote_user: root
  tasks:
    - name: obtain Kerberos ticket
      shell: |
        set timeout 300
        spawn kinit {{ hvp_adjoin_username }}@{{ hvp_adjoin_realm }}
        match_max 100000
        expect -re -nocase "password for.*:.*$"
        send -- "{{ hvp_adjoin_password }}\r"
        expect eof
      args:
        executable: /usr/bin/expect
    - name: join AD domain
      command: net ads join -k osName="CentOS" osVer="7.4.1708"
      register: join_result
    - name: remove Kerberos ticket
      command: kdestroy
      register: kdestroy_result
- name: restart Samba services
  hosts: glusternodes
  remote_user: root
  tasks:
    - name: Signal Samba services to apply the configuration above
      command: smbcontrol all reload-config
      register: smbcontrolreload_result
...
