---
# Ansible playbook for GlusterFS nodes unconfiguration (cleanup)
- name: Generate SSH key if not present
  hosts: localhost
  tasks:
    - include: ../common/tasks/createkeys.yaml
- name: inspect gluster nodes
  hosts: glusternodes
  remote_user: root
  tasks:
    - include: ../common/tasks/setupkeys.yaml
    - name: gather suitable disks
      hvp_free_disks: min_size_bytes=100000000000
    - name: get common vars
      include_vars:
        file: ../common/vars/hvp.yaml
- name: Stop and unconfigure CTDB
  hosts: glusternodes
  remote_user: root
  tasks:
    - name: disable and stop the CTDB service
      systemd:
        name: ctdb
        enabled: False
        state: stopped
        no_block: no
    - name: disable and stop the RT bandwidth configuration
      systemd:
        name: cgroup-rt-bandwidth
        enabled: False
        state: stopped
        no_block: no
    - name: disable and stop the local mounting of the Gluster ctdb volume
      systemd:
        name: gluster-lock.mount
        enabled: False
        state: stopped
        no_block: no
    - name: disable and stop the wait service for Gluster ctdb volume
      systemd:
        name: gluster-ctdb-wait-online
        enabled: False
        state: stopped
        no_block: no
- name: perform gdeploy-based Gluster unconfiguration
  hosts: localhost
  remote_user: root
  tasks:
    - name: prepare gdeploy cleanup configuration file
      template:
        src: templates/gdeploy-cleanup.j2
        dest: "{{ playbook_dir }}/gdeploy-cleanup.conf"
        owner: root
        group: root
        mode: 0644
    - name: perform actual gdeploy-based Gluster unconfiguration
      command: gdeploy -k -vv -c "{{ playbook_dir }}/gdeploy-cleanup.conf"
      register: gdeploy_cleanup_result
...
