---
# Ansible playbook for nodes nic bonding forced LACP setup
# Note: the following will powerdown the nodes at the end so that manual switch configuration can be performed before powering them up again
# Note: the rationale behind this playbook is that LACP seriously interfers both with standard PXE booting and our custom network bonding autodetection logic above - use AP/RR during installation, then use this to convert every bond to LACP afterwards
- name: Generate SSH key if not present
  hosts: localhost
  tasks:
    - include: ../common/tasks/createkeys.yaml
- name: reconfigure gluster nodes bonding to LACP mode
  hosts: glusternodes
  remote_user: root
  tasks:
    - include: ../common/tasks/setupkeys.yaml
    - name: perform actual bonding reconfiguration
      lineinfile: dest="{{ item }}"
                  regexp="^BONDING_OPTS="
                  line="BONDING_OPTS=\"mode=802.3ad xmit_hash_policy=layer2+3 miimon=100\""
                  state=present
      with_fileglob:
        - "/etc/sysconfig/network-scripts/ifcfg-bond*"
    - include: ../common/tasks/shutdown.yaml
...
