---
- name: Generate SSH key if not present
  hosts: localhost
  tasks:
    - include: ../common/tasks/createkeys.yaml
- name: reconfigure gluster nodes bonding to LACP mode
  hosts: glusternodes
  remote_user: root
  tasks:
    - include: ../common/tasks/setupkeys.yaml
    - name: perform actual bonding reconfiguration
      lineinfile: dest="{{ item }}"
                  regexp="^BONDING_OPTS="
                  line="BONDING_OPTS=\"mode=802.3ad xmit_hash_policy=layer2+3 miimon=100\""
                  state=present
      with_fileglob:
        - "/etc/sysconfig/network-scripts/ifcfg-bond*"
    - include: ../common/tasks/shutdown.yaml
...
