---
# Ansible playbook to join the Gluster-based Samba clustered fileserver to the internal oVirt-hosted AD domain
- name: Generate SSH key if not present
  hosts: localhost
  tasks:
    - include_tasks: ../common/tasks/createkeys.yaml
    - name: Get common vars
      include_vars:
        file: "{{ item }}"
      with_items:
        - "../common/vars/hvp.yaml"
        - "../common/vars/ad.yaml"
    - name: Wait for full AD DC availability
      # Note: AD DC identified by resolving the AD domain DNS name
      vars:
        chosen_ad_dc: "{{ lookup('dig', hvp_adjoin_domain, wantlist=True) | first }}"
      # Note: we wait for DNS, RPC, LDAP and Kerberos (password change) services to be listening on a DC
      wait_for:
        host: "{{ chosen_ad_dc }}"
        port: "{{ item }}"
        state: started
        delay: 0
        sleep: 30
        timeout: 300
      with_items:
        - 53
        - 135
        - 389
        - 464
- name: Perform Samba AD configuration
  hosts: glusternodes
  remote_user: root
  tasks:
    - include_tasks: ../common/tasks/setupkeys.yaml
    - name: Get common vars
      include_vars:
        file: "{{ item }}"
      with_items:
        - "../common/vars/hvp.yaml"
        - "../common/vars/ad.yaml"
    - name: Prepare Samba domain-based user-mapping configuration file
      template:
        src: templates/smbusers-domain.j2
        dest: /etc/samba/smbusers
        owner: root
        group: root
        mode: 0644
    - name: Signal Samba services to apply the configuration above
      command: smbcontrol all reload-config
      register: smbcontrolreload_result
    - name: Prepare Samba domain-based main configuration file
      template:
        src: templates/smb-domain.j2
        dest: /etc/samba/smb.conf
        owner: root
        group: root
        mode: 0644
- name: Perform Samba cluster AD joining
  hosts: gluster_master
  remote_user: root
  tasks:
    - name: Obtain Kerberos ticket
      shell: |
        set timeout 300
        spawn kinit {{ hvp_adjoin_username }}@{{ hvp_adjoin_realm }}
        match_max 100000
        expect -re -nocase "password for.*:.*$"
        send -- "{{ hvp_adjoin_password }}\r"
        expect eof
      args:
        executable: /usr/bin/expect
    - name: Join AD domain
      # TODO: use the AD DC identified above to perform AD joining
      shell: net ads join -k osName="$(lsb_release -si)" osVer="$(lsb_release -sr)" createcomputer="File Servers"
      register: join_result
    - name: Add further Kerberos SPNs
      shell: "net ads keytab add {{ item }} -k"
      register: addspn_result
      with_items:
        - cifs
        - nfs
    - name: Extract cluster keytab
      # TODO: either move the keytab in a shared area or replicate it on all nodes
      # TODO: find a way to keep it up-to-date
      # Note: the keytab mainly is needed by NFS-Ganesha for kerberized NFSv4 serving
      shell: net ads keytab create -k
      register: keytabcreate_result
    - name: Grant disk administration privileges to Domain Admins
      shell: "net sam rights grant '{{ hvp_netbios_domainname }}\\Domain Admins' SeDiskOperatorPrivilege -k"
      register: diskprivilegegrant_result
    - name: Remove Kerberos ticket
      command: kdestroy
      register: kdestroy_result
- name: Reload Samba configuration
  hosts: glusternodes
  remote_user: root
  tasks:
    - name: Signal Samba services to apply the configuration above
      command: smbcontrol all reload-config
      register: smbcontrolreload_result
...
