---
# Ansible playbook to configure and start Gluster-block and CTDB/Samba/Gluster-NFS for iSCSI/CIFS/NFS sharing
# TODO: substitute Gluster-NFS with NFS-Ganesha as soon as a proper CTDB-based configuration for NFS-Ganesha has been devised
- name: Generate SSH key if not present
  hosts: localhost
  tasks:
    - include_tasks: ../common/tasks/createkeys.yaml
- name: Inspect Gluster nodes
  hosts: glusternodes
  remote_user: root
  tasks:
    - include_tasks: ../common/tasks/setupkeys.yaml
    - name: Get common vars
      include_vars:
        file: "../common/vars/hvp.yaml"
- name: Prepare Gluster-volume based share dirs for CIFS
  hosts: gluster_master
  remote_user: root
  tasks:
    - name: Mount the Gluster volume intended for CIFS sharing
      command: "mount -t glusterfs localhost:/{{ hvp_winshare_volume_name }} /mnt"
      args:
        warn: no
      register: winsharemount_result
    - name: Create the toplevel folders intended for CIFS sharing
      file:
        path: "/mnt/{{ item.path }}"
        state: directory
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
        mode: "{{ item.mode }}"
      with_items: "{{ hvp_winshare_subfolders }}"
      when: winsharemount_result.rc == 0
    - name: Unmount the Gluster volume intended for CIFS sharing
      command: "umount -l /mnt"
      args:
        warn: no
      register: winshareumount_result
- name: Prepare Gluster-volume based share dirs for NFS
  hosts: gluster_master
  remote_user: root
  tasks:
    - name: Mount the Gluster volume intended for NFS sharing
      command: "mount -t glusterfs localhost:/{{ hvp_unixshare_volume_name }} /mnt"
      args:
        warn: no
      register: unixsharemount_result
    - name: Create the toplevel folders intended for NFS sharing
      file:
        path: "/mnt/{{ item.path }}"
        state: directory
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
        mode: "{{ item.mode }}"
      with_items: "{{ hvp_unixshare_subfolders }}"
      when: unixsharemount_result.rc == 0
    - name: Unmount the Gluster volume intended for NFS sharing
      command: "umount -l /mnt"
      args:
        warn: no
      register: unixshareumount_result
- name: Configure and start Gluster-block
  # TODO: making the basic Gluster-block configuration conditional since it is still somewhat unstable (frequent SIGSEGVs)
  hosts: glusternodes
  remote_user: root
  tasks:
    - name: Remove spurious state file
      file:
        path: /etc/target/saveconfig.json
        state: absent
      when: (hvp_lun_sizes | length) > 0
    - name: Enable and start the Gluster-block service
      systemd:
        name: gluster-blockd
        enabled: true
        state: started
        no_block: no
      when: (hvp_lun_sizes | length) > 0
- name: Create Gluster-block based LUNs
  hosts: gluster_master
  remote_user: root
  tasks:
    - name: Create all Gluster-block based LUNs
      include_tasks: tasks/createlun.yaml
      when: (hvp_lun_sizes | length) > 0
      with_indexed_items: "{{ hvp_lun_sizes }}"
      loop_control:
        loop_var: outer_item
- name: Configure and start CTDB/Samba
  hosts: glusternodes
  remote_user: root
  tasks:
    - name: Enable and start the wait service for Gluster CTDB volume
      systemd:
        name: gluster-ctdb-wait-online
        enabled: true
        state: started
        no_block: no
    - name: Enable and start the local mounting of the Gluster CTDB volume
      systemd:
        name: gluster-lock.mount
        enabled: true
        state: started
        no_block: no
    - name: Enable and start the RT bandwidth configuration
      systemd:
        name: cgroup-rt-bandwidth
        enabled: true
        state: started
        no_block: no
    - name: Prepare Samba Workgroup configuration file
      template:
        src: templates/smb-workgroup.j2
        dest: /etc/samba/smb.conf
        owner: root
        group: root
        mode: 0644
    - name: Enable and start the CTDB service
      systemd:
        name: ctdb
        enabled: true
        state: started
        no_block: no
- name: Configure Samba authentication
  hosts: gluster_master
  remote_user: root
  tasks:
    - name: Wait for Samba to become ready on the host
      wait_for: port=445 timeout=300
    - name: Configure local root user
      shell: "echo -e '{{ ansible_ssh_pass }}\\n{{ ansible_ssh_pass }}\\n' | smbpasswd -s -a root"
      register: smbpasswd_result
...
