# Ansible tasks file to create a single oVirt VM inside a loop (with all parameters passed as outer_item elements)
- name: Create oVirt VM
  ovirt_vms:
    auth: "{{ ovirt_auth }}"
    state: present
    cluster: "{{ cluster_name }}"
    storage_domain: "{{ vmstore_sd_name }}"
    name: "{{ outer_item.vm_name }}"
    comment: "{{ outer_item.vm_comment }}"
    delete_protected: "{{ outer_item.vm_delete_protected }}"
    high_availability: "{{ outer_item.vm_high_availability }}"
    memory: "{{ outer_item.vm_memory }}"
    cpu_cores: "{{ outer_item.vm_cpu_cores }}"
    cpu_sockets: "{{ outer_item.vm_cpu_sockets }}"
    cpu_shares: "{{ outer_item.vm_cpu_shares }}"
    type: "{{ outer_item.vm_type }}"
    operating_system: "{{ outer_item.vm_operating_system }}"
    wait: true
- name: Create oVirt VM disk
  ovirt_disks:
    auth: "{{ ovirt_auth }}"
    state: attached
    name: "{{ outer_item.vm_name }}_disk"
    vm_name: "{{ outer_item.vm_name }}"
    interface: virtio
    format: cow
    storage_domain: "{{ vmstore_sd_name }}"
    size: "{{ outer_item.vm_disk_size }}"
    bootable: true
    wait: true
- name: Create oVirt VM nic
  ovirt_nics:
    auth: "{{ ovirt_auth }}"
    state: plugged
    name: "{{ outer_item.vm_name }}_nic"
    vm: "{{ outer_item.vm_name }}"
    interface: virtio
    network: "{{ outer_item.vm_network_name }}"
    profile: "{{ outer_item.vm_network_name }}"
    wait: true
  register: vmnic_result
- name: Create DHCPd configuration for oVirt VM
  blockinfile:
    path: /etc/dhcp/dhcpd-custom-pxe.conf
    state: present
    create: yes
    owner: root
    group: root
    mode: 0644
    insertafter: EOF
    marker: "# {mark} PXE INSTALL for VM {{ vmnic_result.nic.mac.address | upper }} ANSIBLE MANAGED BLOCK"
    block: |
      if substring (hardware, 1, 6) = {{ vmnic_result.nic.mac.address | upper }} {
        option pxelinux.configfile "pxelinux.cfg/{{ outer_item.vm_kickstart_file | regex_replace('^hvp-([^-]*)-.*$', '\1') }}.cfg";
      }
  register: dhcpdreconf_result
  delegate_to: localhost
- name: Restart DHCPd to apply reconfiguration
  systemd:
    name: dhcpd
    state: restarted
  when: dhcpdreconf_result.changed
  delegate_to: localhost
- name: Start oVirt VM
  ovirt_vms:
    auth: "{{ ovirt_auth }}"
    state: running
    cluster: "{{ cluster_name }}"
    name: "{{ outer_item.vm_name }}"
    boot_devices:
      - hd
      - network
    wait: true
- name: Wait for VM specific service port availability
  wait_for:
    host: "{{ outer_item.vm_service_ip }}"
    port: "{{ outer_item.vm_service_port }}"
    state: started
    connect_timeout: 30
    delay: 600
    sleep: 90
    timeout: 3600
  delegate_to: localhost
