---
# Ansible playbook to completely revert oVirt Hosted Engine setup (cleanup)
# Note: the aim is to undo any effect of running the ovirtnodes.yaml playbook
# Note: this is to be used typically after an aborted/failed Self hosted Engine Setup and before retrying
# Note: no actions/cleanup will be performed on further nodes beyond the master one (that which performs the Engine initial setup)
- name: Generate SSH key if not present
  hosts: localhost
  tasks:
    - include_tasks: ../common/tasks/createkeys.yaml
- name: Inspect oVirt nodes
  hosts: ovirtnodes
  remote_user: root
  tasks:
    - include_tasks: ../common/tasks/setupkeys.yaml
- name: Perform oVirt Hosted Engine cleanup on master node
  hosts: ovirt_master
  remote_user: root
  tasks:
    - name: Get common vars
      include_vars:
        file: ../common/vars/hvp.yaml
    - name: Execute the oVirt Hosted Engine cleanup helper script
      vars:
        ansible_ssh_pipelining: no
      command: ovirt-hosted-engine-cleanup -q
      register: enginecleanup_result
    - name: Mount the Gluster volume intended for Self Hosted Engine
      command: "mount -t glusterfs localhost:/{{ hvp_enginedomain_volume_name }} /mnt"
      args:
        warn: no
      register: enginevolumemount_result
    - name: Find entries inside the Gluster volume intended for Self Hosted Engine
      find:
        paths: "/mnt"
        hidden: true
        recurse: true
        file_type: any
      register: enginevolumeentries_result
    - name: Remove all entries inside the Gluster volume intended for Self Hosted Engine
      file:
        path: "{{ item.path }}"
        state: absent
        # Note: .trashcan and .trashcan/internal_op cannot be deleted, so we must ignore errors
      ignore_errors: yes
      with_items: "{{ enginevolumeentries_result.files }}"
    - name: Unmount the Gluster volume intended for Self Hosted Engine
      command: "umount -l /mnt"
      args:
        warn: no
      register: enginevolumeumount_result
    - name: Remove any leftover libvirt domains
      shell: "for domain in $(virsh list --all --name); do virsh undefine ${domain} --remove-all-storage; done"
      ignore_errors: yes
    - name: Stop and disable oVirt-related services
      systemd:
        name: "{{ item }}"
        state: stopped
        enabled: false
      with_items:
        - mom-vdsm
        - momd
        - ovirt-imageio-daemon
        - supervdsmd
        - vdsm-network-init
        - vdsm-network
        - vdsmd
        - libvirt-guests
        - libvirtd
        - wdmd
    - name: Remove any leftover bridge interfaces
      # TODO: the following does not restore pre-ovirtmgmt network configuration - furthermore it seems that oVirt relies again on legacy network service instead of NetworkManager
      nmcli:
        conn_name: "{{ item }}"
        state: absent
      when: (hostvars[inventory_hostname]['ansible_' + item] is defined) and (hostvars[inventory_hostname]['ansible_' + item]['type'] == 'bridge')
      with_items:
        - "{{ hostvars[inventory_hostname]['ansible_interfaces'] }}"
    - name: Reboot to clean up state
      import_tasks: ../common/tasks/reboot.yaml
...
