---
# Ansible flat tasks file to be included in playbooks
# Note: if a password-containing var has not been defined then the following must be invoked with: --ask-pass
- name: Generate root ECDSA SSH key if not present
  shell: ssh-keygen -q -t ecdsa -b 521 -N "" -f /root/.ssh/id_ecdsa
  args:
    creates: /root/.ssh/id_ecdsa
...
