---
# Ansible flat tasks file to be included in playbooks
- name: Poweroff host
  shell: nohup bash -c "sleep 20 && systemctl poweroff" &
  async: 1
  poll: 0
  register: poweroff_result
- name: Wait for host to go down
  local_action: wait_for host="{{ inventory_hostname }}" port=22 search_regex=OpenSSH state=stopped timeout=300 delay=0 sleep=1
...
