---
# Ansible flat tasks file to be included in playbooks
- name: Poweroff host
  shell: nohup bash -c "sleep 20 && systemctl poweroff" &
  async: 1
  poll: 0
  register: poweroff_result
- name: Wait for host to go down
  wait_for:
    host: "{{ inventory_hostname }}"
    port: 22
    search_regex: "OpenSSH"
    state: stopped
    delay: 10
    sleep: 1
    timeout: 300
  delegate_to: localhost
...
